# Generated by Django 5.0.2 on 2024-02-17 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teammembership_joined_date_alter_team_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('population', models.TextField()),
                ('by_num', models.TextField()),
                ('by_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aims', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('description', models.TextField()),
                ('measure', models.TextField()),
                ('aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.aim')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('stage', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_idea', to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='PDSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.TextField()),
                ('steps', models.TextField()),
                ('measure', models.TextField()),
                ('predictions', models.TextField()),
                ('by_date', models.DateField()),
                ('learning', models.TextField()),
                ('next_step', models.CharField(max_length=255)),
                ('change_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdsa', to='api.changeidea')),
            ],
        ),
    ]
