# Generated by Django 5.0.2 on 2024-02-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aim_driver_changeidea_pdsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeidea',
            name='aim',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='change_idea', to='api.aim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changeidea',
            name='stage',
            field=models.CharField(choices=[('Testing', 'Testing'), ('Implementing', 'Implementing'), ('Spreading', 'Spreading')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='next_step',
            field=models.CharField(choices=[('Implement', 'Implement'), ('Expand', 'Expand'), ('Abandon', 'Abandon')], max_length=255),
        ),
    ]
