# Generated by Django 5.0.2 on 2024-02-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_changeidea_aim_alter_changeidea_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeidea',
            name='aim',
        ),
        migrations.AlterField(
            model_name='changeidea',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_ideas', to='api.driver'),
        ),
    ]
