# Generated by Django 5.0.2 on 2024-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aim_name_changeidea_name_driver_name_pdsa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdsa',
            name='stage',
            field=models.CharField(choices=[('Plan', 'Plan'), ('Do', 'Do'), ('Study', 'Study'), ('Act', 'Act')], default='Plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='aim',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='changeidea',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='changeidea',
            name='stage',
            field=models.CharField(choices=[('Testing', 'Testing'), ('Implementing', 'Implementing'), ('Spreading', 'Spreading')], max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='next_step',
            field=models.CharField(choices=[('Implement', 'Implement'), ('Expand', 'Expand'), ('Abandon', 'Abandon')], max_length=20),
        ),
    ]
