# Generated by Django 5.0.2 on 2024-02-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pdsa_stage_alter_aim_name_alter_changeidea_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsa',
            name='learning',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='next_step',
            field=models.CharField(blank=True, choices=[('Implement', 'Implement'), ('Expand', 'Expand'), ('Abandon', 'Abandon')], max_length=20),
        ),
    ]
