# Generated by Django 5.0.2 on 2024-02-25 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_pdsa_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdsa',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
