# Generated by Django 5.0.2 on 2024-02-25 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pdsa_next_step_rationale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsa',
            name='change_idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdsas', to='api.changeidea'),
        ),
    ]
