# Generated by Django 5.0.2 on 2024-02-25 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pdsa_change_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsa',
            name='by_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='learning_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='measure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='predictions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
