# Generated by Django 5.0.2 on 2024-02-25 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_pdsa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsa',
            name='by_date',
            field=models.DateField(default=datetime.date(2024, 2, 25)),
        ),
    ]
