# Generated by Django 5.0.2 on 2024-02-25 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_pdsa_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsa',
            name='by_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
