# Generated by Django 5.0.2 on 2024-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_pdsa_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsa',
            name='stage',
            field=models.CharField(choices=[('Plan', 'Plan'), ('Do', 'Do'), ('Study', 'Study'), ('Act', 'Act'), ('Complete', 'Complete')], default='Plan', max_length=20),
        ),
    ]
