# Generated by Django 5.0.2 on 2024-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pdsa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeidea',
            name='stage',
            field=models.CharField(choices=[('Abandoned', 'Abandoned'), ('Testing', 'Testing'), ('Implementing', 'Implementing'), ('Spreading', 'Spreading')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pdsa',
            name='next_step',
            field=models.CharField(blank=True, choices=[('Adopt', 'Adopt'), ('Adapt', 'Adapt'), ('Abandon', 'Abandon')], max_length=20),
        ),
    ]
