# Generated by Django 5.0.3 on 2024-03-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pdsa_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aim',
            field=models.TextField(default=''),
        ),
    ]
