# Generated by Django 5.0.3 on 2024-03-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_team_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='aim',
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.team'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aim',
        ),
    ]
