# Generated by Django 5.0.3 on 2024-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_driver_aim_driver_team_delete_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdsa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pdsa',
            name='do_notes',
        ),
        migrations.RemoveField(
            model_name='pdsa',
            name='measure',
        ),
        migrations.AddField(
            model_name='pdsa',
            name='b_measure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pdsa',
            name='o_measure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pdsa',
            name='p_measure',
            field=models.TextField(blank=True),
        ),
    ]
