# Generated by Django 5.0.3 on 2024-03-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_pdsa_data_remove_pdsa_do_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='aim',
            field=models.TextField(blank=True),
        ),
    ]
