# Generated by Django 5.0.3 on 2024-03-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_team_aim'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='is_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
