# Generated by Django 5.0.2 on 2024-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_user_email_5f6a77_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
